name: Build EXE

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy openpyxl selenium pyqt5

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: >
          pyinstaller --noconfirm --clean --onefile --noconsole
          --add-data "drivers/chromedriver.exe;drivers"
          --hidden-import pandas
          --hidden-import numpy
          --hidden-import openpyxl
          --hidden-import PyQt5
          --hidden-import selenium
          yandex_partner_reuploader.py
        shell: pwsh

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: yandex-partner-reuploader
          path: dist/yandex_partner_reuploader.exe
